# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build node.js project
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Rsync files to host
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -armz
        path: build/*
        remote_path: ${{ secrets.UKRENTBOT_DEPLOY_PATH }}
        remote_host: ${{ secrets.UKRENTBOT_DEPLOY_HOST }}
        remote_user: ${{ secrets.UKRENTBOT_DEPLOY_USER }}
        remote_key: ${{ secrets.UKRENTBOT_DEPLOY_KEY }}

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UKRENTBOT_DEPLOY_HOST }}
        username: ${{ secrets.UKRENTBOT_DEPLOY_USER }}
        key: ${{ secrets.UKRENTBOT_DEPLOY_KEY }}
        script: pm2 startOrRestart ${{ secrets.UKRENTBOT_DEPLOY_PATH }}/pm2.config.js 2>&1
